language: rust
rust:
  - 1.28.0 # Minimum supported version
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
      - pulseaudio
      - libpulse-mainloop-glib0
script:
  - dbus-launch pulseaudio --start
  # Check PA v8-11 support
  - cargo build --no-default-features --verbose
  - cargo test --no-default-features --verbose
  # Check PA v12+ support
  # Disabled until travis has an environment with PA v12+ (Bionic, latest, has v11.1)
  #- cargo build --features pa_v12_compatibility --verbose
  #- cargo test --features pa_v12_compatibility --verbose
