[package]
name = "libpulse-sys"
version = "1.11.0"
authors = ["Lyndon Brown <jnqnfe@gmail.com>"]
license = "MIT/Apache-2.0"
description = """
A Rust language linking library for the PulseAudio libpulse library.
"""
keywords = ["sys", "binding", "pulse", "pulseaudio", "audio"]
links = "pulse"
build = "build.rs"
homepage = "https://github.com/jnqnfe/pulse-binding-rust"
repository = "https://github.com/jnqnfe/pulse-binding-rust"
edition = "2018"

[dependencies]
libc = "0.2"

[target.'cfg(target_os="linux")'.build-dependencies]
pkg-config = "0.3"

[features]
default = ["pa_latest_common"]

# PA version compatibility selection
# See the overall project `COMPATIBILITY.md` file for explanation.
#
# Alias targetting latest compatibility, with the exception only of that for a very new release
pa_latest_common = ["pa_v12"]
# Alias simply targetting latest compatibility
pa_latest = ["pa_v13"]
# Enables PA version 13 support
pa_v13 = ["pa_v12"]
# Enables PA version 12 support
pa_v12 = ["pa_v8"]
# Enables PA version 8 support
pa_v8 = ["pa_v6"]
# Enables PA version 6 support
pa_v6 = ["pa_v5"]
# Enables PA version 5 support
pa_v5 = []

# Documentation generation
# This is intended for use with generation of documentation only. It enables inclusion of the latest
# supported PA version features, but without triggering the build script’s pkg-config check.
dox = []

[package.metadata.docs.rs]
features = ["dox"]
all-features = false
no-default-features = true

[badges]
travis-ci = { repository = "jnqnfe/pulse-binding-rust" }
